server:
  port: 8081

dubbo:
  application:
    id:  ghj-serverice-web
    name: ghj-serverice-web
    qos:
      enable: false
  registry:
    id: ghj
    address: zookeeper://127.0.0.1:2181
  qos:
    enabled: false
