server:
  port: 8082
spring:
  datasource:
    name: ghj
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://loaclhost:3306/ghj
mybatis:
  mapper-locations: classpath:authority/*Mapper.xml

dubbo:
  scan:
    base-packages: com.ghj
  application:
    id:  ghj-serverice-provider
    name: ghj-serverice-provider
    qos:
      enable: false
  registry:
    id: ghj
    address: zookeeper://127.0.0.1:2181
  qos:
    enabled: false


