server:
  port: 8082
spring:
  dubbo:
    application: service-provider
    base-package: com.ghj
    registry:
      address: zookeeper://127.0.0.1
  datasource:
    name: ghj
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://loaclhost:3306/ghj
mybatis:
  mapper-locations: classpath:authority/*Mapper.xml
